spring:
  application:
    name: config
server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeguangk/cars
          searchPaths: respo
        username: yeguangk
        password: ye1120242037
    label: master