spring:
  application:
    name: getway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
#  instance:
#    hostname: localhost
#    instance-id: http://localhost:8083
server:
  port: 8083
zuul:
  routes:
    audi:
      path: /audi/**
      serviceId: audi
    bmw:
      path: /bmw/**
      serviceId: bmw