spring:
  application:
    name: config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/yeguangk/cars
            searchPaths: respo
          username: yeguangk
          password: ye1120242037
      label: master

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: config