spring:
  application:
    name: bmw
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8088/
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: bmw
audi:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxAutoReties: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000  # feign 超时控制

